name: fixer
on: [pull_request]
jobs:
  eslint:
    runs-on: ubuntu-latest
    container:
      image: node
      volumes:
        - ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm ci
      - name: run
        run: npx eslint --ext .jsx,.js resources/js
  cs-fixer:
    runs-on: ubuntu-latest
    container:
      image: cytopia/php-cs-fixer
      volumes:
        - ${{ github.workspace }}:/data
    steps:
      - uses: actions/checkout@v3
      - name: run
        run: php-cs-fixer fix --dry-run --diff .
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v2
      - uses: php-actions/phpunit@v9
        with:
          configuration: phpunit.xml
      - run: phpunit
